import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{Bell,Check,ChevronLeft,Dumbbell,Edit3,Home,LogOut,Play,Plus,Save,Timer,TrendingUp,User,Users,X}from'lucide-react';
import'./styles.css';

const STORE='mayfit_v5';
const imageFor=type=>({
 supino:'https://commons.wikimedia.org/wiki/Special:FilePath/Bench%20Press.jpg',
 pelvica:'https://commons.wikimedia.org/wiki/Special:FilePath/Bridge%20%28exercise%29%20-%20USDAgov.jpg',
 legpress:'https://commons.wikimedia.org/wiki/Special:FilePath/Leg%20press%20%28cropped%2C%20flipped%29.jpg',
 flexora:'https://commons.wikimedia.org/wiki/Special:FilePath/LyingLegCurlMachineExercise.JPG',
 panturrilha:'https://commons.wikimedia.org/wiki/Special:FilePath/SeatedCalfRaiseMachineExercise.JPG'
}[type]);

const seed={users:[
 {id:'admin',name:'Samuel',email:'admin@mayfit.com',password:'123456',role:'admin'},
 {id:'aluno',name:'Aluno Teste',email:'aluno@mayfit.com',password:'123456',role:'student'}
],exercises:[
 {id:1,type:'supino',name:'Supino reto',sets:4,reps:12,load:60,previousLoad:56,rest:59,tip:'Pés firmes, escápulas encaixadas e barra descendo até a linha média do peito.'},
 {id:2,type:'pelvica',name:'Elevação pélvica',sets:3,reps:10,load:80,previousLoad:75,rest:60,tip:'Queixo levemente recolhido, abdômen firme e extensão completa do quadril.'},
 {id:3,type:'legpress',name:'Leg Press 90°',sets:4,reps:12,load:120,previousLoad:110,rest:90,tip:'Joelhos alinhados com os pés e lombar apoiada durante todo o movimento.'},
 {id:4,type:'flexora',name:'Cadeira flexora',sets:4,reps:8,load:45,previousLoad:40,rest:60,tip:'Quadril apoiado, movimento controlado e sem tirar o tronco do banco.'},
 {id:5,type:'panturrilha',name:'Panturrilha',sets:4,reps:15,load:50,previousLoad:45,rest:45,tip:'Amplitude completa, subindo na ponta dos pés e descendo devagar.'}
],sessions:[]};
const load=()=>{try{return JSON.parse(localStorage.getItem(STORE))||seed}catch{return seed}};
const save=d=>localStorage.setItem(STORE,JSON.stringify(d));

function Login({data,onLogin}){const[email,setEmail]=useState('aluno@mayfit.com');const[password,setPassword]=useState('123456');const[msg,setMsg]=useState('');const submit=e=>{e.preventDefault();const u=data.users.find(x=>x.email===email&&x.password===password);if(!u)return setMsg('E-mail ou senha incorretos.');onLogin(u)};return <div className="login-page"><div className="login-logo"><span>MaY</span>FiT<small>SEU CORPO. SEU FOCO. SEUS RESULTADOS.</small></div><form className="login-card" onSubmit={submit}><h1>Entrar</h1><label>E-mail<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{msg&&<div className="notice">{msg}</div>}<button className="primary">Entrar</button><button type="button" className="demo-switch" onClick={()=>setEmail(email.includes('admin')?'aluno@mayfit.com':'admin@mayfit.com')}>Alternar conta de teste</button></form></div>}

function ExercisePhoto({exercise,compact=false}){return <div className={compact?'exercise-photo compact':'exercise-photo'}><img src={imageFor(exercise.type)} alt={`Execução correta de ${exercise.name}`}/><span>EXECUÇÃO CORRETA</span></div>}
const format=s=>`${String(Math.floor(Math.max(0,s)/60)).padStart(2,'0')}:${String(Math.max(0,s)%60).padStart(2,'0')}`;
const parseTime=value=>{const clean=value.trim();if(clean.includes(':')){const[m,s]=clean.split(':').map(Number);return Math.max(0,(m||0)*60+(s||0))}return Math.max(0,Number(clean)||0)};

function Workout({data,setData,onBack}){
 const[entries,setEntries]=useState(()=>Object.fromEntries(data.exercises.map(e=>[e.id,{...e}])));
 const[seconds,setSeconds]=useState(data.exercises[0]?.rest||60);const[running,setRunning]=useState(false);const[done,setDone]=useState({});const[timeText,setTimeText]=useState(format(data.exercises[0]?.rest||60));
 useEffect(()=>{setTimeText(format(seconds))},[seconds]);
 useEffect(()=>{if(!running||seconds<=0)return;const id=setInterval(()=>setSeconds(s=>s-1),1000);return()=>clearInterval(id)},[running,seconds]);
 useEffect(()=>{if(seconds===0){setRunning(false);if(navigator.vibrate)navigator.vibrate([250,120,250])}},[seconds]);
 const change=(id,field,value)=>setEntries(old=>({...old,[id]:{...old[id],[field]:value}}));
 const useTime=e=>{const value=Number(entries[e.id].rest)||0;setSeconds(value);setRunning(false)};
 const conclude=e=>{const completed=!done[e.id];setDone(old=>({...old,[e.id]:completed}));if(completed){setSeconds(Number(entries[e.id].rest)||0);setRunning(true)}};
 const finish=()=>{const updated=data.exercises.map(e=>({...e,...entries[e.id],load:Number(entries[e.id].load)||0,previousLoad:Number(entries[e.id].previousLoad)||0,sets:Number(entries[e.id].sets)||1,reps:Number(entries[e.id].reps)||1,rest:Number(entries[e.id].rest)||0}));setData({...data,exercises:updated,sessions:[...data.sessions,{id:crypto.randomUUID(),date:new Date().toISOString()}]});alert('Treino salvo com sucesso!');onBack()};
 return <section className="workout-screen"><div className="workout-top"><button className="icon back-button" onClick={onBack}><ChevronLeft/></button><div className="time-strip"><span>TEMPO</span><input aria-label="Tempo do cronômetro" value={timeText} onChange={e=>setTimeText(e.target.value)} onBlur={()=>{const value=parseTime(timeText);setSeconds(value);setTimeText(format(value))}}/><button className="icon" onClick={()=>setRunning(!running)}>{running?<Timer/>:<Bell/>}</button></div></div><div className="sheet"><div className="sheet-head"><span>EXERCÍCIO</span><span>CARGA</span><span>SÉRIES</span><span>PROGRESSÃO</span></div>{data.exercises.map(e=>{const v=entries[e.id];const progress=(Number(v.load)||0)-(Number(v.previousLoad)||0);return <article className={done[e.id]?'sheet-row done':'sheet-row'} key={e.id}><div className="exercise-col"><strong>{e.name}</strong><ExercisePhoto exercise={e}/><small>{e.tip}</small></div><div className="cell load-cell"><label>Atual<input type="number" value={v.load} onChange={x=>change(e.id,'load',x.target.value)}/></label><label>Anterior<input type="number" value={v.previousLoad} onChange={x=>change(e.id,'previousLoad',x.target.value)}/></label><span>kg</span></div><div className="cell series-cell"><div className="series-pair"><label>Séries<input type="number" min="1" value={v.sets} onChange={x=>change(e.id,'sets',x.target.value)}/></label><b>×</b><label>Reps<input type="number" min="1" value={v.reps} onChange={x=>change(e.id,'reps',x.target.value)}/></label></div><label className="rest-label">Tempo (s)<input type="number" min="0" value={v.rest} onChange={x=>change(e.id,'rest',x.target.value)}/></label><button className="time-button" onClick={()=>useTime(e)}>Usar tempo</button></div><div className="cell progress-cell"><strong className={progress>=0?'positive':'negative'}>{progress>=0?'+':''}{progress} kg</strong><button className="complete-button" onClick={()=>conclude(e)}>{done[e.id]?<><Check/>Feito</>:'Concluir'}</button></div></article>})}</div><button className="primary finish" onClick={finish}><Save/>Finalizar e salvar treino</button></section>
}

function Admin({data,setData}){const[editing,setEditing]=useState(null);const update=(id,field,value)=>setData({...data,exercises:data.exercises.map(e=>e.id===id?{...e,[field]:['sets','reps','load','previousLoad','rest'].includes(field)?Number(value):value}:e)});const add=()=>{const id=Math.max(0,...data.exercises.map(e=>e.id))+1;setData({...data,exercises:[...data.exercises,{id,type:'supino',name:'Novo exercício',sets:3,reps:12,load:0,previousLoad:0,rest:60,tip:'Descreva a execução correta.'}]});setEditing(id)};return <section><div className="section-title"><h1>Gerenciar treino</h1><button className="small" onClick={add}><Plus/>Novo</button></div><p className="muted">Edite exercício, figura, carga, séries, repetições e tempo individual.</p><div className="admin-list">{data.exercises.map(e=><article className="admin-card" key={e.id}><div className="admin-head"><ExercisePhoto exercise={e} compact/><div><strong>{e.name}</strong><span>{e.sets} × {e.reps} • {e.load} kg • {e.rest}s</span></div><button className="icon" onClick={()=>setEditing(editing===e.id?null:e.id)}>{editing===e.id?<X/>:<Edit3/>}</button></div>{editing===e.id&&<div className="edit-grid"><label>Nome<input value={e.name} onChange={x=>update(e.id,'name',x.target.value)}/></label><label>Figura<select value={e.type} onChange={x=>update(e.id,'type',x.target.value)}><option value="supino">Supino</option><option value="pelvica">Elevação pélvica</option><option value="legpress">Leg press</option><option value="flexora">Cadeira flexora</option><option value="panturrilha">Panturrilha</option></select></label><label>Carga atual<input type="number" value={e.load} onChange={x=>update(e.id,'load',x.target.value)}/></label><label>Carga anterior<input type="number" value={e.previousLoad} onChange={x=>update(e.id,'previousLoad',x.target.value)}/></label><label>Séries<input type="number" value={e.sets} onChange={x=>update(e.id,'sets',x.target.value)}/></label><label>Repetições<input type="number" value={e.reps} onChange={x=>update(e.id,'reps',x.target.value)}/></label><label>Tempo escolhido (s)<input type="number" value={e.rest} onChange={x=>update(e.id,'rest',x.target.value)}/></label><label className="full">Orientação<textarea value={e.tip} onChange={x=>update(e.id,'tip',x.target.value)}/></label></div>}</article>)}</div></section>}

function App(){const[data,setData]=useState(load);const[user,setUser]=useState(()=>{try{return JSON.parse(sessionStorage.getItem('mayfit_user'))}catch{return null}});const[tab,setTab]=useState('inicio');const[workout,setWorkout]=useState(false);useEffect(()=>save(data),[data]);const login=u=>{setUser(u);sessionStorage.setItem('mayfit_user',JSON.stringify(u))};const logout=()=>{setUser(null);sessionStorage.removeItem('mayfit_user')};if(!user)return <Login data={data} onLogin={login}/>;if(workout)return <div className="app"><Workout data={data} setData={setData} onBack={()=>setWorkout(false)}/></div>;const admin=user.role==='admin';return <div className="app"><header><div className="logo"><span>MaY</span>FiT<small>{admin?'Gerenciamento':'Área do aluno'}</small></div><button className="icon"><Bell/></button></header><main>{admin?<Admin data={data} setData={setData}/>:<>{tab==='inicio'&&<><section className="hero"><span>TREINO DO DIA</span><h1>Treino A</h1><p>{data.exercises.length} exercícios • tudo editável</p><button className="primary" onClick={()=>setWorkout(true)}><Play/>Iniciar treino</button></section><div className="summary"><article><Dumbbell/><strong>{data.exercises.length}</strong><span>Exercícios</span></article><article><TrendingUp/><strong>{data.sessions.length}</strong><span>Treinos salvos</span></article></div></>}{tab==='treinos'&&<><div className="section-title"><h1>Meu treino</h1><button className="small" onClick={()=>setWorkout(true)}><Play/>Abrir</button></div><div className="preview-list">{data.exercises.map(e=><article key={e.id}><ExercisePhoto exercise={e} compact/><div><strong>{e.name}</strong><span>{e.sets} × {e.reps} • {e.load} kg • {e.rest}s</span></div></article>)}</div></>}{tab==='perfil'&&<section className="profile"><div className="avatar">{user.name[0]}</div><h1>{user.name}</h1><p>{user.email}</p><button className="danger" onClick={logout}><LogOut/>Sair</button></section>}</>}</main><nav>{admin?<><button className="active"><Users/><span>Gerenciar</span></button><button onClick={()=>{const aluno=data.users.find(u=>u.id==='aluno');setUser(aluno);sessionStorage.setItem('mayfit_user',JSON.stringify(aluno))}}><User/><span>Ver aluno</span></button><button onClick={logout}><LogOut/><span>Sair</span></button></>:<><button className={tab==='inicio'?'active':''} onClick={()=>setTab('inicio')}><Home/><span>Início</span></button><button className={tab==='treinos'?'active':''} onClick={()=>setTab('treinos')}><Dumbbell/><span>Treinos</span></button><button className={tab==='perfil'?'active':''} onClick={()=>setTab('perfil')}><User/><span>Perfil</span></button></>}</nav></div>}
createRoot(document.getElementById('root')).render(<App/>);