import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Activity,Bell,Check,ChevronRight,Dumbbell,Home,LogOut,Play,Plus,Save,Search,Timer,TrendingUp,User,Users,Weight,Edit3,X}from'lucide-react';
import'./styles.css';

const STORE='mayfit_v1';
const seed={
 users:[
  {id:'admin',name:'Samuel',email:'admin@mayfit.com',password:'123456',role:'admin',status:'active',phone:'(69) 98481-0587'},
  {id:'aluno',name:'Aluno Teste',email:'aluno@mayfit.com',password:'123456',role:'student',status:'active',phone:'(69) 99999-0000'}
 ],
 exercises:[
  {id:1,type:'supino',name:'Supino reto',sets:4,reps:12,load:60,rest:90,muscle:'Peito',tip:'Pés firmes, escápulas encaixadas e barra descendo até a linha média do peito.'},
  {id:2,type:'inclinado',name:'Supino inclinado',sets:4,reps:12,load:45,rest:90,muscle:'Peito superior',tip:'Banco entre 30° e 45°, punhos alinhados e movimento controlado.'},
  {id:3,type:'crucifixo',name:'Crucifixo com halteres',sets:3,reps:15,load:16,rest:60,muscle:'Peito',tip:'Cotovelos levemente flexionados e amplitude sem forçar os ombros.'},
  {id:4,type:'triceps',name:'Tríceps na polia',sets:3,reps:15,load:35,rest:60,muscle:'Tríceps',tip:'Cotovelos fixos ao lado do corpo e extensão completa sem balançar o tronco.'},
  {id:5,type:'flexao',name:'Flexão de braços',sets:3,reps:12,load:0,rest:60,muscle:'Peito e core',tip:'Corpo alinhado, abdômen firme e peito descendo entre as mãos.'}
 ],
 measurements:[{id:1,userId:'aluno',date:'2026-05-01',weight:87.5,waist:86},{id:2,userId:'aluno',date:'2026-06-01',weight:84.9,waist:84},{id:3,userId:'aluno',date:'2026-07-28',weight:82.5,waist:82}],
 sessions:[]
};
const load=()=>{try{return JSON.parse(localStorage.getItem(STORE))||seed}catch{return seed}};
const save=d=>localStorage.setItem(STORE,JSON.stringify(d));

function ExerciseGuide({type,compact=false}){const poses={
 supino:{label:'Supino reto',a:<><line x1="20"y1="102"x2="160"y2="102"/><circle cx="66"cy="76"r="10"/><line x1="76"y1="80"x2="124"y2="92"/><line x1="90"y1="82"x2="90"y2="42"/><line x1="116"y1="89"x2="116"y2="42"/><line className="accent"x1="68"y1="42"x2="138"y2="42"/></>,b:<><line x1="20"y1="102"x2="160"y2="102"/><circle cx="66"cy="76"r="10"/><line x1="76"y1="80"x2="124"y2="92"/><line x1="90"y1="82"x2="100"y2="62"/><line x1="116"y1="89"x2="108"y2="62"/><line className="accent"x1="68"y1="62"x2="138"y2="62"/></>},
 inclinado:{label:'Supino inclinado',a:<><line x1="35"y1="116"x2="132"y2="72"/><circle cx="72"cy="72"r="10"/><line x1="82"y1="78"x2="118"y2="94"/><line x1="90"y1="81"x2="90"y2="42"/><line x1="112"y1="91"x2="112"y2="42"/><line className="accent"x1="68"y1="42"x2="134"y2="42"/></>,b:<><line x1="35"y1="116"x2="132"y2="72"/><circle cx="72"cy="72"r="10"/><line x1="82"y1="78"x2="118"y2="94"/><line x1="90"y1="81"x2="99"y2="62"/><line x1="112"y1="91"x2="107"y2="62"/><line className="accent"x1="68"y1="62"x2="134"y2="62"/></>},
 crucifixo:{label:'Crucifixo',a:<><line x1="20"y1="104"x2="160"y2="104"/><circle cx="70"cy="78"r="10"/><line x1="80"y1="82"x2="124"y2="94"/><line x1="92"y1="84"x2="65"y2="54"/><line x1="114"y1="91"x2="142"y2="56"/><rect className="accent-fill"x="56"y="49"width="18"height="8"rx="3"/><rect className="accent-fill"x="138"y="51"width="18"height="8"rx="3"/></>,b:<><line x1="20"y1="104"x2="160"y2="104"/><circle cx="70"cy="78"r="10"/><line x1="80"y1="82"x2="124"y2="94"/><line x1="92"y1="84"x2="101"y2="54"/><line x1="114"y1="91"x2="109"y2="54"/><rect className="accent-fill"x="92"y="48"width="18"height="8"rx="3"/><rect className="accent-fill"x="106"y="48"width="18"height="8"rx="3"/></>},
 triceps:{label:'Tríceps na polia',a:<><line x1="146"y1="20"x2="146"y2="132"/><circle cx="78"cy="38"r="10"/><line x1="78"y1="49"x2="82"y2="92"/><line x1="82"y1="92"x2="66"y2="132"/><line x1="82"y1="92"x2="98"y2="132"/><line x1="82"y1="60"x2="108"y2="68"/><line x1="108"y1="68"x2="116"y2="88"/><line className="accent"x1="116"y1="88"x2="146"y2="20"/></>,b:<><line x1="146"y1="20"x2="146"y2="132"/><circle cx="78"cy="38"r="10"/><line x1="78"y1="49"x2="82"y2="92"/><line x1="82"y1="92"x2="66"y2="132"/><line x1="82"y1="92"x2="98"y2="132"/><line x1="82"y1="60"x2="108"y2="68"/><line x1="108"y1="68"x2="114"y2="112"/><line className="accent"x1="114"y1="112"x2="146"y2="20"/></>},
 flexao:{label:'Flexão de braços',a:<><line x1="18"y1="128"x2="162"y2="128"/><circle cx="48"cy="68"r="10"/><line x1="58"y1="73"x2="118"y2="90"/><line x1="118"y1="90"x2="150"y2="120"/><line x1="80"y1="79"x2="70"y2="124"/><line x1="108"y1="88"x2="102"y2="124"/></>,b:<><line x1="18"y1="128"x2="162"y2="128"/><circle cx="48"cy="92"r="10"/><line x1="58"y1="96"x2="118"y2="106"/><line x1="118"y1="106"x2="150"y2="122"/><line x1="80"y1="100"x2="72"y2="124"/><line x1="108"y1="105"x2="103"y2="124"/></>}};const p=poses[type]||poses.supino;const Frame=({title,children})=><div className="guide-frame"><small>{title}</small><svg viewBox="0 0 180 145"role="img"aria-label={`${p.label} ${title}`}>{children}</svg></div>;return <div className={compact?'exercise-guide compact':'exercise-guide'}><Frame title="INÍCIO">{p.a}</Frame>{!compact&&<><b className="guide-arrow">→</b><Frame title="FINAL">{p.b}</Frame></>}</div>}

function Login({data,setData,onLogin}){const[mode,setMode]=useState('login');const[form,setForm]=useState({name:'',email:'',password:'',phone:''});const[msg,setMsg]=useState('');
 const submit=e=>{e.preventDefault();setMsg('');if(mode==='login'){const u=data.users.find(x=>x.email.toLowerCase()===form.email.toLowerCase()&&x.password===form.password);if(!u)return setMsg('E-mail ou senha incorretos.');if(u.status!=='active')return setMsg('Conta ainda não liberada.');onLogin(u);return}if(!form.name||!form.email||form.password.length<6)return setMsg('Preencha os dados e use senha com 6 caracteres.');if(data.users.some(x=>x.email===form.email))return setMsg('Este e-mail já está cadastrado.');const u={id:crypto.randomUUID(),...form,role:'student',status:'pending'};const next={...data,users:[...data.users,u]};setData(next);save(next);setMsg('Cadastro enviado. Aguarde aprovação do administrador.');setMode('login')};
 return <div className="auth"><div className="auth-logo"><span>MaY</span>FiT<small>SEU CORPO. SEU FOCO. SEUS RESULTADOS.</small></div><form className="panel" onSubmit={submit}><h1>{mode==='login'?'Entrar':'Criar conta'}</h1><p>{mode==='login'?'Bem-vindo de volta!':'Comece sua evolução hoje.'}</p>{mode==='signup'&&<><label>Nome completo<input value={form.name}onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Telefone<input value={form.phone}onChange={e=>setForm({...form,phone:e.target.value})}/></label></>}<label>E-mail<input type="email"value={form.email}onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Senha<input type="password"value={form.password}onChange={e=>setForm({...form,password:e.target.value})}/></label>{msg&&<div className="notice">{msg}</div>}<button className="primary">{mode==='login'?'Entrar':'Criar conta'}</button><button type="button"className="link"onClick={()=>{setMode(mode==='login'?'signup':'login');setMsg('')}}>{mode==='login'?'Criar conta':'Já tenho conta'}</button><div className="demo">Teste: <b>admin@mayfit.com</b> ou <b>aluno@mayfit.com</b><br/>Senha: <b>123456</b></div></form></div>}

function App(){const[data,setData]=useState(load);const[user,setUser]=useState(()=>{try{return JSON.parse(sessionStorage.getItem('mayfit_user'))}catch{return null}});const[tab,setTab]=useState('inicio');const[active,setActive]=useState(null);const[done,setDone]=useState({});const[seconds,setSeconds]=useState(0);const[search,setSearch]=useState('');const[editing,setEditing]=useState(null);
 useEffect(()=>save(data),[data]);useEffect(()=>{if(seconds<=0)return;const t=setInterval(()=>setSeconds(s=>s-1),1000);return()=>clearInterval(t)},[seconds]);
 const login=u=>{setUser(u);sessionStorage.setItem('mayfit_user',JSON.stringify(u))};const logout=()=>{setUser(null);sessionStorage.removeItem('mayfit_user')};
 if(!user)return <Login data={data}setData={setData}onLogin={login}/>;
 const isAdmin=user.role==='admin';const measurements=data.measurements.filter(m=>m.userId===user.id||(!isAdmin&&user.id==='aluno')).sort((a,b)=>a.date.localeCompare(b.date));const current=measurements.at(-1);
 const finish=()=>{const s={id:crypto.randomUUID(),userId:user.id,date:new Date().toISOString(),workout:'Treino A',completed:Object.keys(done).length};setData({...data,sessions:[...data.sessions,s]});setActive(null);setDone({});alert('Treino salvo com sucesso!')};
 const approve=id=>setData({...data,users:data.users.map(u=>u.id===id?{...u,status:'active'}:u)});const block=id=>setData({...data,users:data.users.map(u=>u.id===id?{...u,status:u.status==='blocked'?'active':'blocked'}:u)});const updateExercise=(id,field,value)=>setData({...data,exercises:data.exercises.map(e=>e.id===id?{...e,[field]:['sets','reps','load','rest'].includes(field)?Number(value):value}:e)});const addExercise=()=>{const id=Math.max(0,...data.exercises.map(e=>Number(e.id)))+1;setData({...data,exercises:[...data.exercises,{id,type:'supino',name:'Novo exercício',sets:3,reps:12,load:0,rest:60,muscle:'Grupo muscular',tip:'Descreva aqui a execução correta.'}]});setEditing(id)};const removeExercise=id=>setData({...data,exercises:data.exercises.filter(e=>e.id!==id)});
 const addMeasure=e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const m={id:crypto.randomUUID(),userId:user.id,date:new Date().toISOString().slice(0,10),weight:Number(fd.get('weight')),waist:Number(fd.get('waist'))||null};setData({...data,measurements:[...data.measurements,m]});e.currentTarget.reset()};
 const nav=isAdmin?[['inicio',Home,'Painel'],['alunos',Users,'Alunos'],['treinos',Dumbbell,'Treinos'],['perfil',User,'Perfil']]:[['inicio',Home,'Início'],['treinos',Dumbbell,'Treinos'],['progresso',TrendingUp,'Progresso'],['perfil',User,'Perfil']];
 return <div className="app"><header><div className="logo"><span>MaY</span>FiT<small>{isAdmin?'Painel administrativo':'Seu corpo. Seu foco.'}</small></div><button className="icon"><Bell size={20}/></button></header><main>
 {active?<section><button className="back"onClick={()=>setActive(null)}>← Voltar</button><h1>Treino A</h1><p className="muted">Peito e tríceps • {data.exercises.length} exercícios</p>{seconds>0&&<div className="timer"><Timer/> Descanso: <b>{seconds}s</b></div>}<div className="stack">{data.exercises.map((e,i)=><article className={done[e.id]?'exercise done':'exercise'}key={e.id}><ExerciseGuide type={e.type}/><div className="exercise-info"><div className="num">{done[e.id]?<Check/>:i+1}</div><div className="grow"><b>{e.name}</b><span>{e.muscle} • {e.sets} séries × {e.reps} reps • {e.load?`${e.load} kg`:'Peso corporal'}</span><small>{e.tip}</small></div><button className="small"onClick={()=>{setDone({...done,[e.id]:!done[e.id]});if(!done[e.id])setSeconds(e.rest)}}>{done[e.id]?'Feito':'Concluir'}</button></div></article>)}</div><button className="primary fixed-action"onClick={finish}><Save/> Finalizar e salvar treino</button></section>:
 <>
 {tab==='inicio'&&!isAdmin&&<><section className="welcome"><div><p>Olá, {user.name.split(' ')[0]} 👋</p><h1>Seu próximo resultado começa agora.</h1></div><div className="ring">{Math.min(100,data.sessions.filter(s=>s.userId===user.id).length*10+30)}%</div></section><section className="hero"><span>PRÓXIMO TREINO</span><h2>Treino A — Peito e tríceps</h2><p>{data.exercises.length} exercícios • cerca de 45 minutos</p><button className="primary"onClick={()=>setActive('A')}><Play fill="currentColor"/> Iniciar treino</button></section><div className="grid"><article><Dumbbell/><b>{data.sessions.filter(s=>s.userId===user.id).length}</b><span>Treinos realizados</span></article><article><Weight/><b>{current?.weight||'—'} kg</b><span>Peso atual</span></article></div><h2>Atalhos</h2><div className="quick"><button onClick={()=>setTab('treinos')}><Dumbbell/>Treinos</button><button onClick={()=>setTab('progresso')}><TrendingUp/>Progresso</button><button onClick={()=>setTab('perfil')}><User/>Perfil</button></div></>}
 {tab==='inicio'&&isAdmin&&<><h1>Painel</h1><div className="grid admin-grid"><article><Users/><b>{data.users.filter(u=>u.role==='student'&&u.status==='active').length}</b><span>Alunos ativos</span></article><article><User/><b>{data.users.filter(u=>u.status==='pending').length}</b><span>Solicitações</span></article><article><Activity/><b>{data.sessions.length}</b><span>Treinos registrados</span></article><article><TrendingUp/><b>{data.measurements.length}</b><span>Medições salvas</span></article></div><h2>Solicitações recentes</h2>{data.users.filter(u=>u.status==='pending').map(u=><article className="student"key={u.id}><div className="avatar">{u.name[0]}</div><div className="grow"><b>{u.name}</b><span>{u.phone||u.email}</span></div><button className="small"onClick={()=>approve(u.id)}>Aprovar</button></article>)}</>}
 {tab==='alunos'&&isAdmin&&<><h1>Alunos</h1><div className="search"><Search/><input placeholder="Buscar nome ou telefone"value={search}onChange={e=>setSearch(e.target.value)}/></div>{data.users.filter(u=>u.role==='student'&&(u.name+u.phone).toLowerCase().includes(search.toLowerCase())).map(u=><article className="student"key={u.id}><div className="avatar">{u.name[0]}</div><div className="grow"><b>{u.name}</b><span>{u.phone||u.email}</span><small className={'status '+u.status}>{u.status}</small></div>{u.status==='pending'?<button className="small"onClick={()=>approve(u.id)}>Aprovar</button>:<button className="small secondary"onClick={()=>block(u.id)}>{u.status==='blocked'?'Liberar':'Bloquear'}</button>}</article>)}</>}
 {tab==='treinos'&&<><div className="title-row"><h1>{isAdmin?'Gerenciar treinos':'Meus treinos'}</h1>{isAdmin&&<button className="small"onClick={addExercise}><Plus/>Novo exercício</button>}</div>{isAdmin?<div className="stack">{data.exercises.map(e=><article className="editor-card"key={e.id}><div className="editor-head"><ExerciseGuide type={e.type}compact/><div className="grow"><b>{e.name}</b><span>{e.muscle}</span></div><button className="icon"onClick={()=>setEditing(editing===e.id?null:e.id)}>{editing===e.id?<X/>:<Edit3/>}</button></div>{editing===e.id&&<div className="editor-grid"><label>Nome<input value={e.name}onChange={x=>updateExercise(e.id,'name',x.target.value)}/></label><label>Grupo muscular<input value={e.muscle}onChange={x=>updateExercise(e.id,'muscle',x.target.value)}/></label><label>Tipo visual<select value={e.type}onChange={x=>updateExercise(e.id,'type',x.target.value)}><option value="supino">Supino reto</option><option value="inclinado">Supino inclinado</option><option value="crucifixo">Crucifixo</option><option value="triceps">Tríceps polia</option><option value="flexao">Flexão</option></select></label><label>Séries<input type="number"value={e.sets}onChange={x=>updateExercise(e.id,'sets',x.target.value)}/></label><label>Repetições<input type="number"value={e.reps}onChange={x=>updateExercise(e.id,'reps',x.target.value)}/></label><label>Carga (kg)<input type="number"value={e.load}onChange={x=>updateExercise(e.id,'load',x.target.value)}/></label><label>Descanso (s)<input type="number"value={e.rest}onChange={x=>updateExercise(e.id,'rest',x.target.value)}/></label><label className="full">Orientação<textarea value={e.tip}onChange={x=>updateExercise(e.id,'tip',x.target.value)}/></label><button className="danger full"onClick={()=>removeExercise(e.id)}>Excluir exercício</button></div>}</article>)}</div>:<><article className="plan"><div><b>Treino A</b><span>Peito e tríceps • {data.exercises.length} exercícios</span></div><button className="icon"onClick={()=>setActive('A')}><ChevronRight/></button></article><div className="stack">{data.exercises.map(e=><article className="exercise-preview"key={e.id}><ExerciseGuide type={e.type}compact/><div className="grow"><b>{e.name}</b><span>{e.sets} × {e.reps} • {e.load?`${e.load} kg`:'Peso corporal'}</span></div></article>)}</div></>}</>}
 {tab==='progresso'&&!isAdmin&&<><h1>Progresso</h1><article className="chart"><div className="title-row"><div><span>Peso atual</span><h2>{current?.weight||'—'} kg</h2></div><b className="green">{measurements.length>1?(current.weight-measurements[0].weight).toFixed(1):0} kg</b></div><div className="bars">{measurements.map(m=><i key={m.id}style={{height:`${Math.max(25,100-(m.weight-75)*3)}%`}}title={`${m.weight} kg`}/>)}</div></article><form className="panel compact"onSubmit={addMeasure}><h2>Nova medição</h2><label>Peso (kg)<input name="weight"type="number"step="0.1"required/></label><label>Cintura (cm)<input name="waist"type="number"step="0.1"/></label><button className="primary">Salvar medição</button></form><h2>Histórico</h2>{measurements.slice().reverse().map(m=><article className="history"key={m.id}><div><b>{m.weight} kg</b><span>{m.waist?`Cintura: ${m.waist} cm`:''}</span></div><small>{new Date(m.date+'T12:00').toLocaleDateString('pt-BR')}</small></article>)}</>}
 {tab==='perfil'&&<><div className="profile"><div className="big-avatar">{user.name[0]}</div><h1>{user.name}</h1><p>{isAdmin?'Administrador':'Aluno MaYFiT'}</p></div><article className="panel compact"><div className="row"><span>E-mail</span><b>{user.email}</b></div><div className="row"><span>Status</span><b>{user.status}</b></div><div className="row"><span>Dados salvos</span><b>neste aparelho</b></div><button className="danger"onClick={logout}><LogOut/> Sair da conta</button></article></>}
 </>}
 </main>{!active&&<nav>{nav.map(([id,Icon,label])=><button key={id}className={tab===id?'active':''}onClick={()=>setTab(id)}><Icon/><span>{label}</span></button>)}</nav>}</div>}

if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
createRoot(document.getElementById('root')).render(<App/>);